name: GitHub Actions Deploy 
on: [push]
branches: 
  - dev
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
      - run: pytest .tests/core.py
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "programacion-robots-pilot" 
          heroku_email: "branchi468@gmail.com"
